using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using PropertyApi.Models;

using PdfUnit = QuestPDF.Infrastructure.Unit;

namespace PropertyApi.Services;



public interface IInvoicePdfService
{
    byte[] Generate(Invoice invoice);
}


public class InvoicePdfService : IInvoicePdfService
{
    
    static InvoicePdfService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] Generate(Invoice invoice)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2.5f, PdfUnit.Centimetre);
                page.DefaultTextStyle(t => t.FontFamily("Arial").FontSize(11));

                // ── Header 
                page.Header().Row(row =>
                {
                    row.RelativeItem().Column(col =>
                    {
                        col.Item()
                           .Text("PropertyCloud")
                           .Bold()
                           .FontSize(22)
                           .FontColor(Color.FromHex("#4F46E5")); 

                        col.Item()
                           .Text("Property Management Platform")
                           .FontSize(10)
                           .FontColor(Color.FromHex("#6B7280")); 
                    });

                    row.ConstantItem(160).AlignRight().Column(col =>
                    {
                        col.Item().Text("INVOICE").Bold().FontSize(18);
                        col.Item().Text($"#{invoice.Id.ToString()[..8].ToUpper()}")
                           .FontSize(10)
                           .FontColor(Color.FromHex("#6B7280"));
                    });
                });

                // ── Divider ───────────────────────────────────────────────────
                page.Header().PaddingTop(8)
                    .LineHorizontal(1).LineColor(Color.FromHex("#E5E7EB"));

                // ── Body 
                page.Content().PaddingTop(24).Column(col =>
                {
                    
                    col.Item().Row(r =>
                    {
                        r.AutoItem()
                         .Background(StatusColor(invoice.Status))
                         .PaddingVertical(4f).PaddingHorizontal(8f)
                         .Text(invoice.Status.ToUpper())
                         .Bold()
                         .FontSize(10)
                         .FontColor(Colors.White);
                    });

                    col.Item().PaddingTop(20);

                    // Details table
                    col.Item().Table(t =>
                    {
                        t.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn(2);
                            c.RelativeColumn(3);
                        });

                        void Row(string label, string value)
                        {
                            t.Cell().Padding(6).Text(label)
                             .FontColor(Color.FromHex("#6B7280"));
                            t.Cell().Padding(6).Text(value).Bold();
                        }

                        Row("Invoice ID", invoice.Id.ToString());
                        Row("Type", ToTitleCase(invoice.Type));
                        Row("Lease ID", invoice.LeaseId.ToString());
                        Row("Due Date", invoice.DueDate.ToString("d MMM yyyy"));
                        Row("Paid Date", invoice.PaidDate?.ToString("d MMM yyyy") ?? "—");
                    });

                    col.Item().PaddingTop(24);


                    col.Item()
                       .Background(Color.FromHex("#EEF2FF")) 
                       .Padding(16)
                       .Row(r =>
                       {
                           r.RelativeItem().Text("Total Amount (MYR)")
                            .Bold()
                            .FontSize(13);

                           r.AutoItem()
                            .Text($"MYR {invoice.Amount:N2}")
                            .Bold()
                            .FontSize(20)
                            .FontColor(Color.FromHex("#4F46E5"));
                       });

                    col.Item().PaddingTop(32);

                    
                    col.Item()
                       .Text("This is a system-generated invoice and does not require a signature.")
                       .Italic()
                       .FontSize(9)
                       .FontColor(Color.FromHex("#9CA3AF"));
                });

                // ── Footer 
                page.Footer().AlignCenter()
                    .Text(t =>
                    {
                        t.Span("Generated by PropertyCloud · Page ")
                         .FontSize(9)
                         .FontColor(Color.FromHex("#9CA3AF"));
                        t.CurrentPageNumber().FontSize(9).FontColor(Color.FromHex("#9CA3AF"));
                        t.Span(" of ").FontSize(9).FontColor(Color.FromHex("#9CA3AF"));
                        t.TotalPages().FontSize(9).FontColor(Color.FromHex("#9CA3AF"));
                    });
            });
        });

        return document.GeneratePdf();
    }

    // ── Helpers
    private static string StatusColor(string status) => status switch
    {
        "paid" => "#16A34A", 
        "overdue" => "#DC2626", 
        "cancelled" => "#6B7280", 
        _ => "#D97706"  
    };

    private static string ToTitleCase(string s) =>
        string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s[1..];
}